

import React from 'react'
import {types, Instance, SnapshotIn, onSnapshot, destroy, applySnapshot, getSnapshot } from "mobx-state-tree";
import { newTodoStore, TodoStore } from '@/root/index';
import StoreProvider from '@/root/Provider';
import './globals.css'
import type { Metadata } from 'next'
// import { setupRootStore } from "./mst/setup";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo application',
  description: 'Generated by Ebunoluwa',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
       <StoreProvider value={newTodoStore }>
          <main className="container">{children }</main>
      </StoreProvider>
      </body>
    </html>
  )
}
