import React from 'react'
// import { Provider } from "mobx-react-lite";
import './globals.css'
import type { Metadata } from 'next'
// import { setupRootStore } from "./mst/setup";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo application',
  description: 'Generated by Ebunoluwa',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <main className="container">{children}</main>
        </body>
    </html>
  )
}
